# Quarkus LangChain4j Configuration
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b
quarkus.langchain4j.ollama.timeout=300s
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

# RAG Personalized Configurations
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

# PGVector Configurations
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true

## EASY RAG Configuration
#quarkus.langchain4j.easy-rag.path=src/main/java/org/israelgda/resources/rag
##Setting the segment size to produce smaller chunks
#quarkus.langchain4j.easy-rag.max-segment-size=100
##Setting the overlap size to produce adequate context connections between chunks
#quarkus.langchain4j.easy-rag.max-overlap-size=20